### ISSUE TITLE
Unable to Deploy to Azure, fails trying to use old image

### ISSUE THREAD

**Issue by robertmcdaniel** [Microsoft/ml-server-image-similarity#4]
Problem
Trying to deploy a new Data Science windows 2016 VM using a Github Template, but facing error "microsoft-ads:windows-data-science-vm:windows2016:18.02.00' is not available.".

Root Cause
Template is using an outdated SKU for the VM image

**Comment by jeroenterheerdt** [comment]
this was fixed in #5 .
